sudo: required
dist: trusty
language: c

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
            - openmpi-bin
            - openmpi-dev

script:
    - ./autogen.sh && ./configure
    - make -j 8
    - cd test ; make check
