sudo: required
dist: trusty
language: c

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
            - openmpi-bin
            - openmpi-dev

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; brew update ; brew install openmpi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; sudo apt-get -qq update ; apt-get -qq install openmpi-dev openmpi-bin

script:
    - ./autogen.sh && ./configure
    - make -j 8
    - cd test ; make check
